[package]
name = "amd-catalyst-fw-extractor"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[profile.release]
strip = true

[dependencies]
binaryninja = { git = "https://github.com/Vector35/binaryninja-api.git", branch = "dev", version = "0.1.0" }
rfd = "0.15.0"
